apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: gitea/gitea:1.22-rootless
          ports:
            - containerPort: 3000
          env:
            - name: GITEA__database__DB_TYPE
              value: sqlite3
            - name: GITEA__database__PATH
              value: /var/lib/gitea/data/gitea.db
            - name: GITEA__server__HTTP_PORT
              value: "3000"
            - name: GITEA__server__ROOT_URL
              value: http://localhost:3000/
            - name: GITEA__security__INSTALL_LOCK
              value: "true"
            - name: GITEA__security__SECRET_KEY
              value: localdevsecretkey
            - name: GITEA__service__DISABLE_REGISTRATION
              value: "true"
          volumeMounts:
            - name: data
              mountPath: /var/lib/gitea
      volumes:
        - name: data
          emptyDir: {}
